version: '3'
services:
  web-server:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:80"
    container_name: web-server
    depends_on:
      - notebook
  notebook:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/var/www
    container_name: notebook
    depends_on:
      - database
  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=Notebooks
    ports:
      - '5000:5432'
    container_name: postgres
